#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

set -u

function usage() {
    echo -n \
"Usage: $(basename "$0")
Build container images from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        sed -e "s/%%STATSD_VERSION%%/${STATSD_VERSION}/" \
            -e "s/%%STATSD_LIBRATO_BACKEND_VERSION%%/${STATSD_LIBRATO_BACKEND_VERSION}/" \
            "Dockerfile-${VARIANT}.template" > Dockerfile

        docker \
            build -t "quay.io/azavea/statsd:${STATSD_VERSION:0:3}-${VARIANT}" .

        docker images
    fi
fi
